name: CI Pipeline
on:
  pull_request:
    branches: [main]

jobs:
  quality_checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: TypeScript type check
        run: npx tsc --noEmit

      - name: ESLint (Next.js)
        run: npm run lint

      - name: Prettier check (with Tailwind plugin)
        run: npx prettier --check . --plugin prettier-plugin-tailwindcss

      - name: Unit tests (Vitest)
        run: npm run test:unit
